# -*- coding: utf-8 -*-
"""AI_Practical821ipynb__2026_10_04_13_45_11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKWL6Ngy1b_1q_MD6_o-5TtmOme9CHj2

# Practical8: Mini AI Text Classification Application

**Objective:** Develop a mini AI application and report on ethics and explainability considerations.

In this practical, we will build one very small **Spam Message Classifier**.

The application will read a short message and predict whether it is:

- `Spam`
- `Not Spam`

We will use:

- `CountVectorizer` to turn words into numbers.
- `MultinomialNB` as a simple text classification model.

## 1. What Will Our AI Application Do?

The application receives a message such as:

```text
Win a free prize now
```

and gives a prediction such as:

```text
Spam
```

Another message such as:

```text
Please attend the meeting tomorrow
```

may be predicted as:

```text
Not Spam
```

This is a simple example of **text classification**.

## 2. Import the Required Libraries

We will use two tools from `scikit-learn`:

- `CountVectorizer` converts text into numbers.
- `MultinomialNB` learns how to classify the messages.
"""

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

"""## 3. Create a Small Training Dataset

We need a few example messages to teach the model.

Each message has a label:

- `Spam`
- `Not Spam`

"""

messages = [
    "Win a free prize now",
    "Claim your free reward",
    "Congratulations you won cash",
    "Get a special offer today",
    "Please attend the meeting tomorrow",
    "Can we meet after class",
    "Your assignment is due Friday",
    "Please please send me the notes"
]

labels = [
    "Spam",
    "Spam",
    "Spam",
    "Spam",
    "Not Spam",
    "Not Spam",
    "Not Spam",
    "Not Spam"
]

"""## 4. Convert the Text Into Numbers

A machine-learning model cannot directly work with words.

`CountVectorizer` counts words and converts the messages into numbers.

"""

# Creating the CountVectorizer
vectorizer = CountVectorizer()

# Creating the vocabulary and transforming the tokens
X = vectorizer.fit_transform(messages)

print("Vocabulary: ", vectorizer.vocabulary_)
print(X.toarray())

"""### Understanding the code

```python
vectorizer = CountVectorizer()
```

creates the text converter.

Then:

```python
X = vectorizer.fit_transform(messages)
```

reads the training messages and converts them into numerical data that the model can use.

## 5. Train the Classifier

Now we create the Naive Bayes classifier and train it.
"""

model = MultinomialNB()

model.fit(X,labels)

"""### Understanding the code

```python
model = MultinomialNB()
```

creates the classifier.

Then:

```python
model.fit(X, labels)
```

teaches the model using:

- `X` = the messages converted into numbers
- `labels` = the correct class for each message

## 6. Test the AI Application

Now we give the model a new message.

The new message must first be converted using the same `vectorizer`.
"""

new_message = ["Win cash today"]

new_X = vectorizer.transform(new_message)

prediction = model.predict(new_X)

print("Message:", new_message[0])
print("Prediction:", prediction[0])

"""### Expected Result

The model should predict:

```text
Spam
```

The model has seen words such as `win` and `cash` in the spam examples, so these words help it make the prediction.

## 7. Let the User Enter a Message

Now we turn the classifier into a very small application.

The user types a message and the model predicts its class.
"""

user_message = input("Enter a message: ")

user_X = vectorizer.transform([user_message])

prediction = model.predict(user_X)

print("Prediction:", prediction[0])

"""## 8. How the Application Works

The complete flow is:

```text
User enters a message
        ↓
CountVectorizer converts words into numbers
        ↓
Naive Bayes classifier checks the pattern
        ↓
Spam or Not Spam
```

This is a small but complete AI text-classification application.

# 9. Ethics Considerations

Even a small AI classifier can create problems if it is used carelessly.

### 1. Wrong predictions

The model can make mistakes.

A normal message may be marked as spam, or a spam message may be missed.

So important decisions should not depend only on this small model.

### 2. Bias in the training data

The model learns from the examples we give it.

If the training examples are poor or unbalanced, the predictions may also be poor or unfair.

### 3. Privacy

Real messages may contain private information.

A real system should protect user data and should not collect or share messages without a valid reason and proper permission.

# 10. Explainability Considerations

We should be able to give a simple explanation of why the model made a prediction.

In this practical, the model works from the words found in the training messages.

For example, words such as:

```text
win
free
reward
cash
offer
```

appear in our spam examples.

So when a new message contains similar words, the model may be more likely to predict `Spam`.

This is a simple form of explanation.

However, the prediction is still based on the whole pattern learned by the model, so one word alone does not always decide the answer.

> **Main idea:** Users should know what information the model uses and should also know that its prediction can be wrong.

## 11. Quick Recap

In this practical:

- We created a small text-classification dataset.
- `CountVectorizer` converted text into numbers.
- `MultinomialNB` learned to classify messages.
- The user could enter a new message.
- The application predicted `Spam` or `Not Spam`.
- We discussed **ethics**, including errors, bias, and privacy.
- We discussed **explainability**, including how words can influence the prediction.

> **Main idea:** A mini AI application combines data, a model, input, and a prediction, but we must also think about how reliable, fair, private, and understandable the system is.
"""