# -*- coding: utf-8 -*-
"""AI P5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-ctu7mE-ozGr-jE5eLywPTQj-7tt3iz
"""

Build a small rule based expert system or logic inference

def laptop_advisor(turn_on,internet,slow):
  if turn_on == "no":
    print("Ceck the charger and power cable")
  elif internet=="no":
    print("Check the wifi connection")
  elif slow =="yes":
    print("Restart the laptopand close the unused programs")
  else:
    print("The system does not find any problems")
turn_on=input("Does the laptop turn on?yes/no:")
internet=input("Is there any internet connection?yes/no:")
slow=input("Is the laptop slow?yes/no:")
advise=laptop_advisor(turn_on,internet,slow)
print("E xport system advise")
print(advise)